
* Knowledge Curation in a Developer Community: A Study of Stack Overflow and Mailing Lists

This is the dataset that accompanies the following publications:

- "Knowledge Curation in a Developer Community: A Study of Stack Overflow and Mailing Lists" by Carlos G칩mez Teshima. MSc. Thesis, University of Victoria, 2015 ([[https://dspace.library.uvic.ca/handle/1828/7011][view publication]])
- "How the R Community Creates and Curates Knowledge" by Alexey Zagalsky, Carlos G칩mez Teshima, Daniel M. German, Margaret-Anne Storey, Germ치n Poo-Caama침o. The 13th International Conference on Mining Software Repositories, 2016 ([[http://dl.acm.org/citation.cfm?id=2901772][view publication]])

** Contents

- LimeSurvey report - survey answers.pdf. It contains the survey answers. The report is printed version of the online report generated by Lime Survey. 

- *R-ML-and-StackOverflow-psql-sample.tar.xz. This is a SQL dump (postgresql) of the database of emails and Stackoverflow
  samples used in the study. The file was compressed using xz. To create the database run the following:
  (using Linux)

#+begin_src 
cat R-ML-and-StackOverflow-psql-sample.tar.xz | xzcat > r_ml_so.dump
#+end_src

And then load the dump using [pg_restore](https://www.postgresql.org/docs/8.1/static/app-pgrestore.html):

#+begin_src 
pg_restore -h localhost -p 5432 -U postgres -d sampledb -v "r_ml_so.dump"
#+end_src

This will create a database called MLandSOF. The decompressed file is a SQL script that can be read by pgsql.

- *R-ML-and-StackOverflow-psql.xz-part00 t0 R-ML-and-StackOverflow-psql.xz-part05*. This is a SQL dump (postgresql) of the database of emails and Stackoverflow
  questions used. The file was compressed using xz and split (due to github restrictions regarding file size). To create the database run the following:
  (using Linux)

#+begin_src 
cat R-ML-and-StackOverflow-psql.xz-part* | xzcat | pgsql template1
#+end_src

This will create a database called MLandSOF.  Under Windows, first concatenate the files (in order, -part00 to -part05), then decompress. The decompressed file is a SQL script that can be read by pgsql.




